### PR TITLE
Add a Dockerfile for the packaging

### PR DESCRIPTION
**Pull request by jpiron**

### CODE REVIEW

**Comment by philippmeisberger** [comment]
I do not know Docker ;) What are the benefits compared to `dpkg-buildpackage -uc -us` for building the package?

**Comment by jpiron** [comment]
It doesn't build differently. The Docker container runs `dpkg-buildpackage -uc -us`. Actually it runs `debuild -uc -us`. From what I read `debuild` is a wrapper around `dpkg-buildpackage` that performs additional checks (I really don't master Debian packaging :) ).
The benefit of Docker here is to perform the packaging within a Debian 8 sandbox without having to install all the build utilities on your host. And regardless of what your host is (Centos, Debian, Ubuntu, ...) the build will be performed the exact same way.

**Comment by philippmeisberger** [comment]
You are right: `debuild` is a wrapper command. Docker sounds nice ;) But IMHO `dpkg-buildpackage -uc -us` is the easier way for those users who want to simple compile the latest version of DDNS-Updater on their own machine. After all the most stable version is distributed over the PM Code Works repository. 

On your request: I improved the readme and described how to compile the package. Docker seems to be a professional tool for building large number of packages. Since Python and its setup-tools are only needed Docker is maybe not necessary.

**Comment by jpiron** [comment]
Indeed, I mostly created it for me to play around with Debian packaging without messing up my environment :) 
This is not really necessary.

**Pull request closed without merging**
